apiVersion: v1
data:
  exporter.conf: |
    [General]
    metricsFile=/var/www/html/metrics
    addLabels=method
    addStatusGroupLabel=status
    collectBytesTransferred=bytes_sent

    [LogFormats]
    %{HOSTNAME:hostname}(:%{INT:port})? %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent} (%{QS:referrer}|-) (%{QS:agent}|-)
    %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent} (%{QS:referrer}|-) (%{QS:agent}|-)
    %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent}

    [/var/lib/docker/containers/*]
    type=kubernetes
    labels={ "instance.ip" : "${HOSTIP}", "instance.hostname" : "${HOSTNAME}" }
kind: ConfigMap
metadata:
  name: httpd-exporter-config
  namespace: monitoring
---
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use extensions/v1beta1
kind: DaemonSet
metadata:
  name: httpd-exporter
  namespace: monitoring
  labels:
    app: httpd-exporter
spec:
  selector:
    matchLabels:
      name: httpd-exporter
  template:
    metadata:
      labels:
        name: httpd-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: httpd-exporter
        image: technicalguru/httpd-exporter:alpha
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: etcconfig
          mountPath: /etc/httpd-exporter
        - name: varwww
          mountPath: /var/www/html
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcconfig
        configMap:
          name: httpd-exporter-config
      - name: varwww
        hostPath:
          path: /var/www/html
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
