apiVersion: v1
data:
  default.conf: |
    server {
        listen       9386;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
            location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: httpd-config
  namespace: monitoring
---
---
apiVersion: v1
data:
  exporter.conf: |
    [General]
    metricsFile=/var/www/html/metrics
    addLabels=method
    addStatusGroupLabel=status
    collectBytesTransferred=bytes_sent
    retentionSeconds=3600
    deadLabels=method,status

    [LogFormats]
    %{HOSTNAME:hostname}(:%{INT:port})? %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent} (%{QS:referrer}|-) (%{QS:agent}|-)
    %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent} (%{QS:referrer}|-) (%{QS:agent}|-)
    %{IP:clientip} %{NOTSPACE:rlogname} %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{REQUEST_LINE}" %{INT:status} %{INT:bytes_sent}

    [/var/lib/docker/containers/*]
    type=kubernetes
    labels={ "instance.ip" : "${HOSTIP}", "instance.hostname" : "${HOSTNAME}" }
kind: ConfigMap
metadata:
  name: httpd-exporter-config
  namespace: monitoring
---
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use extensions/v1beta1
kind: DaemonSet
metadata:
  name: httpd-exporter
  namespace: monitoring
  labels:
    app: httpd-exporter
spec:
  selector:
    matchLabels:
      name: httpd-exporter
  template:
    metadata:
      labels:
        name: httpd-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: httpd-exporter
        image: technicalguru/httpd-exporter:current
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: etcconfig
          mountPath: /etc/httpd-exporter
        - name: varwww
          mountPath: /var/www/html
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      - name: httpd
        image: nginx
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 9386
          name: httpd-exporter
        env:
        - name: NGINX_PORT
          value: "9386"
        volumeMounts:
        - name: nginxconfig
          mountPath: /etc/nginx/conf.d
        - name: varwww
          mountPath: /usr/share/nginx/html
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etcconfig
        configMap:
          name: httpd-exporter-config
      - name: nginxconfig
        configMap:
          name: httpd-config
      - name: varwww
        hostPath:
          path: /var/www/html
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
